[package]
name = "leds-arduino"
version = "0.1.0"
edition = "2021"

[dependencies]
ruduino = {  git = "https://github.com/avr-rust/ruduino", branch = "master", features = ["all-mcus"] }

[profile.release]
lto = true
